#!/bin/bash

if echo $1 | egrep "install" >&/dev/null
then if [ -e `cat ~/vpackage-path.log`/packages/$2/install ]
	then curl -L "`cat ~/vpackage-path.log`/packages/$2/install" | bash 
	else echo "vpackage: Fehler: Ungültiges Paket"
	fi
elif echo $1 | egrep "update" >&/dev/null
	then if echo $2 | egrep -v "." >&/dev/null
		then cd "`cat ~/vpackage-path.log`" ; git pull
		else if [ -e "`cat vpackage-path.log`/$2/update" ]
			then curl -L "`cat vpackage-path.log`/$2/update" | bash
			else echo "vpackage: Fehler: Diese Anwendung exestiert nicht oder ist nicht aktuallisierbar."
			fi
		fi
	fi
elif echo $1  | egrep "uninstall" >&/dev/null
	then REMOVE_PATH="`cat ~/vpackage-path`/packages/$2/uninstall"
		if [ -e "`cat ~/vpackage-path`/packages/$2/uninstall" ]
		then curl -L $REMOVE_PATH | bash 
		else echo "vpackage: Fehler: Diese Anwendung exestiert nicht oder ist nicht (mit vpackage) löschbar."
		fi
	fi
elif echo $1 | egrep list >&/dev/null  
then cat "`cat ~/vpackage-path.log`/list"
else echo "vpackage Hilfe" ; cat "`cat ~/vpackage-path.log`/help"
fi