#!/bin/bash
if librewolf $1
then exit 0
elif firefox $1
then exit 0
elif chromium-browser
then exit 0
elif chromium $1
then exit 0
elif google-chrome $1
	#whereis -b google-chrome | cut -f 2 -d ":" | cut -f 2 -d " " >&/dev/null
then exit 0
else exit 1
fi