#!/bin/bash

if [ -e /usr/bin/lxterminal ]
then lxterminal -e "vpackage $1 $2 ; echo fertig ;read"
elif [ -e /usr/bin/xfce4-terminal ]
then xfce4-terminal -e "vpackage $1 $2 ; echo fertig ;read"
elif [ -e /usr/bin/uxterm ]
then uxterm -e "vpackage $1 $2 ; echo fertig ; read"
elif [ -e /usr/bin/xterm ]
then xterm -e "vpackage $1 $2 ; echo fertig ; read"
else python3 -c '\
from tkinter import * 
Fenster=Tk()
Fenster.title("Fehler")
Anzeige=Label(Fenster, text="Es ist kein vorgegebenes Terminal in der Liste, dass auf ihrem System verfügbar ist.\nAktuallisieren sie das oder fordern sie ein PR auf.")
Anzeige.pack()
Fenster.mainloop()'
fi